### ISSUE TITLE
Парочка кейзов за 2 минуты

### ISSUE THREAD

**Issue by hisubbotin** [valentinburk/equations-parser#1]
Как насчет:
```
x+1=2 ?
+x = 0 
x^+1=0
```
Вообще странно, когда такая программа падает в лицо ошибкой :)

**Comment by valentinburk** [comment]
Поправлено. 

1. Теперь все предложенные варианты считаются валидными. Для степени можно явно указать, что она положительная: `x^+2=y => x^2-y=0`
2. Расширены тест-кейсы: добавлены несколько негативов
3. Приложение больше не падает при исключительных ситуациях. Вместо этого пользователю выводится сервисное сообщение уровня `Error`, в то время как явно невалидное уравнение (т.е. когда выброшено `InvalidEquationException`) теперь возвращается с уровнем `Warning`.
